#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'optparse'
require 'codenet_bugs'
require 'codenet_bugs/bugs'
require 'codenet_bugs/tests'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: evaluate [options]"

  opts.on('--checkpoint PATH', "Continue evaluating from checkpoint (e.g., in case of a crash)") do |checkpoint|
    options[:checkpoint] = checkpoint
  end
end.parse!

preds_filename = ARGV.first

bugs = CodenetBugs::Bugs.load_internal :valid #, preds_filename
tests = CodenetBugs::Tests.load_internal

bugs.evaluate! tests, checkpoint: options[:checkpoint]

