#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'optparse'
require 'run_bug_run'
require 'run_bug_run/bugs'
require 'run_bug_run/tests'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: evaluate [options]"

  opts.on('--checkpoint PATH', "Continue evaluating from checkpoint (e.g., in case of a crash)") do |checkpoint|
    options[:checkpoint] = checkpoint
  end

  opts.on('-o PATH', "Output filename") do |output_filename|
    options[:output_filename] = output_filename
  end
end.parse!

preds_filename = ARGV.first

bugs = RunBugRun::Bugs.load_internal :test, preds_filename
tests = RunBugRun::Tests.load_internal

bugs.evaluate! tests, checkpoint: options[:checkpoint], output_filename: options[:output_filename]

